version: '3.8'

services: 

  scraper-app:
    build: ./scraper_app
    command: uvicorn app.endpoints:app --host 0.0.0.0 --reload
    hostname: scraper-api
    volumes:
      - ./scraper_app:/usr/src/app/
    ports:
      - 8004:8000
    environment: 
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: 
      - redis


  worker:
      build: ./scraper_app
      command: python3 -m celery -A computing.tasks.celery_app worker #--loglevel=DEBUG
      volumes:
        - ./scraper_app:/usr/src/app
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - scraper-app
        - redis


  redis:
    image: redis:6-alpine


  history-app:
    build: ./history_app
    command: uvicorn app.endpoints:app --host 0.0.0.0 --reload
    hostname: history-app
    volumes:
      - ./history_app:/usr/src/app/
    ports:
      - 8005:8000
    depends_on:
      - scraper-app
  

  ui-app:
    build: ./ui_app
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        python3 manage.py makemigrations
        python3 manage.py migrate && python3 manage.py migrate --run-syncdb
        python3 manage.py runserver localhost:8000
    ports:
      - 8006:8000


