version: '3.8'

services: 

  scraper_api:
    build: ./scraper_api
    command: uvicorn endpoints:app --host 0.0.0.0 --reload
    volumes:
      - ./scraper_api:/usr/src/app/
    ports:
      - 8004:8000
    environment: 
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: 
      - redis
  
  
  worker:
      build: ./scraper_api
      command: python3 -m celery -A computing.tasks.celery_app worker #--loglevel=DEBUG
      volumes:
        - ./scraper_api:/usr/src/app
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - scraper_api
        - redis

  redis:
    image: redis:6-alpine

    
  history_app:
    build: ./history_app
    command: uvicorn endpoints:app --host 0.0.0.0 --reload
    volumes:
      - ./history_app:/usr/src/app/
    ports:
      - 8005:8000
    depends_on:
      - scraper_api
