name: CI & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up check-out
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest, docker-compose, docker
      - name: Run docker-compose
        run: docker-compose up --build
      - name: Open container with app
        run: docker exec -it scraper-app bash
      - name: run tests
        run: python -m pytest app/tests/main_test.py
