name: CI & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
       JWT_SECRET: ${{ secrets.JWT_SECRET }}
       JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
       API_AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
       SCRAPER_APP_ADMIN_LOGIN: ${{ secrets.SCRAPER_APP_ADMIN_LOGIN }}
       SCRAPER_APP_ADMIN_PASSWORD: ${{ secrets.SCRAPER_APP_ADMIN_PASSWORD }}
       HISTORY_APP_DB: ${{ secrets.HISTORY_APP_DB }}
       HISTORY_APP_DB_USER: ${{ secrets.HISTORY_APP_DB_USER }}
       HISTORY_APP_DB_PASSWORD: ${{ secrets.HISTORY_APP_DB_PASSWORD }}

    steps:
      - name: Set up check-out
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install scraper_app dependencies & run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r ./services/scraper_app/requirements.txt
          python -m pytest ./services/scraper_app/app/tests/main_test.py

      - name: Install history_app dependencies & run tests
        run: | 
          python -m pip install --upgrade pip
          pip install -r ./services/history_app/requirements.txt
          python -m pytest ./services/history_app/app/tests/main_test.py
